---
title: "Dashboard"
author: "GTA"
date: "08/10/2019"
output: html_document
---

```{r setup, include=FALSE, warning = F, echo = F, render= F, results = "hide"}

knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(ggplot2)
library(ggthemes)
library(graphics)
library(forcats)
library(scales)
library(extrafont)
```

```{r loading, include=TRUE, echo = F, results = "hide", warning=FALSE, render = F}
source("./nettoyage.R")
```

## Carte de Partenaires par Province 

```{r progres, results='asis', warnings = FALSE, echo=FALSE}
parternaires_exec = data %>% 
  filter(Statut == "compl_t") 

nombre_parternaires_exec = parternaires_exec %>% 
  select(Acteur_Organisation_de_mise_en_uvre) %>% unique %>% nrow

cat("Nombre de partenaires avec interventions:",nombre_parternaires_exec,"</b><br>")

parternaires_exec_p = comptage_par_admin(df = parternaires_exec,
                                            nom.admin = province,
                                            nom.partenaires = "Acteur_Organisation_de_mise_en_uvre")

partenaires_exec_carte = carte_complete(donnees_groupees =
                                          parternaires_exec_p, 
                                        shapefile = Province, 
                                        nom.admin.donnees = "province",
                                        nom.admin.shapefile = "NOM", 
                                        variable = "Acteur_Organisation_de_mise_en_uvre")

couleurs <- couleurs_pour_carte("Blues", nombre = length(unique(partenaires_exec_carte$Acteur_Organisation_de_mise_en_uvre)))

ggplot(partenaires_exec_carte) + 
  geom_sf(aes(fill = factor(Acteur_Organisation_de_mise_en_uvre))) + 
  scale_fill_manual(values = couleurs) + 
  labs(fill = "Partenaires avec interventions") + 
  theme(text = element_text(family = "Arial Narrow"))

```

```{r plannnned, results='asis', warnings = FALSE, echo=FALSE}
parternaires_planifie = data %>% 
  filter(Statut == "planifi") 

nombre_parternaires_planifie = parternaires_planifie %>% 
  select(Acteur_Organisation_de_mise_en_uvre) %>% unique %>% nrow

cat("Nombre de partenaires avec interventions:",nombre_parternaires_planifie,"</b><br>")

parternaires_planifie_p = comptage_par_admin(df = parternaires_planifie,
                                            nom.admin = province,
                                            nom.partenaires = "Acteur_Organisation_de_mise_en_uvre")

partenaires_plan_carte = carte_complete(donnees_groupees =
                                          parternaires_planifie_p, 
                                        shapefile = Province, 
                                        nom.admin.donnees = "province",
                                        nom.admin.shapefile = "NOM", 
                                        variable = "Acteur_Organisation_de_mise_en_uvre")

couleurs <- couleurs_pour_carte("Blues", nombre = length(unique(partenaires_plan_carte$Acteur_Organisation_de_mise_en_uvre)))

ggplot(partenaires_plan_carte) + 
  geom_sf(aes(fill = factor(Acteur_Organisation_de_mise_en_uvre))) + 
  labs(fill = "Partenaires avec interventions planifiees") + 
   scale_fill_manual(values = couleurs) + 
  theme(text = element_text(family = "Arial Narrow"))

```

## Interventions par partenaire et bailleur pour chaque Zone de Sante


```{r partenaires, results='asis', warnings = FALSE, echo=FALSE}

Partenaires <- data %>%  
  select(Acteur_Organisation_de_mise_en_uvre, Bailleurs_de_fonds, zonesante) %>% 
  dplyr::group_by(zonesante) %>%  
  nest() %>%  
  mutate(Bailleurs = map(data, function(df) unique(df$Bailleurs_de_fonds))) %>%  mutate(Partenaire = map(data, function(df)unique(df$Acteur_Organisation_de_mise_en_uvre)))

Partenaires$Bailleurs = map_to_labels_outside(Partenaires$Bailleurs, "Bailleurs_de_fonds", questionnaire)

Partenaires$Partenaire = map_to_labels_outside(Partenaires$Partenaire, "Acteur_Organisation_de_mise_en_uvre", questionnaire)

Partenaires$zonesante = map_to_labels_outside(Partenaires$zonesante, "zonesante", questionnaire)
            
Partenaires %>% 
  select(zonesante, Partenaire, Bailleurs) %>% 
  kable(format = "markdown")

```


## Montant de projets par Zone et bailleurs

```{r montant_zone, echo=FALSE,warnings = FALSE}

stats_fp = aggregate(data$prix_USD, list(data$province), sum, na.rm = T)
names(stats_fp) = c("Province", "Somme_projets")
stats_fp <- stats_fp %>% filter(., Somme_projets > 0) 

stats_fp = stats_fp[order(- stats_fp$Somme_projets),] # Pour les avoir dans le bon ordre
stats_fp$Province <- factor(stats_fp$Province, levels = stats_fp$Province) # bloquer l'ordre

Plot_beef = ggplot(stats_fp, aes(x = Province, 
        y = Somme_projets), fill = reach_style_color_red(1)) + 
        geom_bar(stat = "identity") + theme_classic() + ylab("Montant Total") +
        xlab("Province") + theme(text = element_text(family = "Arial Narrow")) 
                                 
cat("Somme des activites par province")
Plot_beef + scale_y_continuous(labels = comma)

fp_projets = aggregate(data$prix_USD, list(data$Bailleurs_de_fonds), sum, na.rm = T)
names(fp_projets) = c("Bailleurs", "Somme_projets")
fp_projets  %<>% filter(Somme_projets > 0) 

cat("Quantite totale des fonds par Bailleur en USD")

fp_projets = fp_projets[order(fp_projets$Somme_projets),] # Pour les avoir dans le bon ordre
fp_projets$Bailleurs = map_to_labels_outside(fp_projets$Bailleurs, "Bailleurs_de_fonds", questionnaire)

fp_projets$Bailleurs <- factor(fp_projets$Bailleurs, levels = fp_projets$Bailleurs) # bloquer l'ordre

Bailleurs = ggplot(fp_projets, aes(x = Somme_projets, 
        y = Bailleurs), fill = reach_style_color_red(1), size = 16) + 
  geom_point(stat = "identity", color = "#EE5859") +
        xlab("Montant") + theme(text = element_text(family = "Arial Narrow") 
        #axis.title.x = element_blank(), axis.title.y = element_blank()
        ) 

Bailleurs + scale_x_continuous(labels = comma)
```

## Manque et gaps

```{r beneficiaires, echo = FALSE, warnings = FALSE}

personnes_couvertes = aggregate(data$menages_projet, list(data$province), sum, na.rm = T)
names(personnes_couvertes) = c("Province", "menages")

personnes_couvertes %<>% mutate(Personnes = menages * 5)


targets = aggregate(targets$target_hno_2019, list(targets$Province), sum, na.rm = T)
names(targets) = c("Province", "Target")


personnes_couvertes_ye = merge(x = personnes_couvertes, 
                                y = targets, 
                                by.x = "Province", 
                                by.y = "Province", 
                                all.y = T)  %>% mutate(Ratio = 1 - (menages/Target))

carte_gap <- personnes_couvertes_ye %>% carte_complete(donnees_groupees = .,
                                          shapefile = Province,
                                          nom.admin.donnees = "Province", nom.admin.shapefile = "NOM", variable = "Ratio")

couleurs <- couleurs_pour_carte("Reds", nombre = 30)

ggplot(carte_gap) + 
  geom_sf(aes(fill = factor(Ratio))) + 
  scale_fill_manual(values = couleurs) + 
  labs(fill = "% Gap in each province") + 
  theme(text = element_text(family = "Arial Narrow"))

```

## Types de beneficiaires

```{r type_benef, echo = FALSE, warnings = FALSE}
# 
# doooo = data[questionnaire$choices_for_select_multiple("type_de_b_n_ficiaires", data)]
# 
# chacun = doooo %>% lapply(., function(x, y)sum(x, na.rm = T)) %>% unlist

#Pourque ceci colle vraiment il faudra ensuite le tout par 

homes = aggregate(data$menages_projet, list(data$type_de_b_n_ficiaires), sum, na.rm = T)
names(homes) = c("Type", "Total_Personnes")
homes %<>% filter(Total_Personnes > 0) 

# Pour les avoir dans le bon ordre
homes = homes[order(homes$Total_Personnes),]
# lock in factor level order
homes$Type <- factor(homes$Type, levels = homes$Type)
# homes <- within(homes, Total_Personnes <- factor(Total_Personnes, 
# levels=names(sort(table(Total_Personnes), # decreasing=TRUE))))
                                                       
Plot_benef = ggplot(homes, aes(x= Type, y = Total_Personnes), fill = reach_style_color_red(1)) + 
        geom_col() + theme(text = element_text(family = "Arial Narrow")) + xlab("Total de personnes") + ylab("Type de beneficiare") + coord_flip()
       # axis.title.x = element_blank(), axis.title.y = element_blank()

Plot_benef
```
